### ISSUE TITLE
dotnet: consider emitting namespace, class, method, and field/property names referenced by an assembly

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1013]
(1) e.g. emit the following for `System.IO.File::OpenRead`:

```yaml
- namespace: System.IO
- class: File
- method: OpenRead
```

(2) be more explicit to avoid FPs resulting from naming conflicts, e.g.:

```yaml
- namespace: System.IO
- class: System.IO.File
- method: System.IO.File::OpenRead
```

and for properties, e.g. (more discussion in #939):

```yaml
- namespace: System.Net
- class: System.Net.WebRequest
- property: System.Net.WebRequest::Method
```

I like option 2 the best, and I think this would apply to both file and function scopes and both internal and external references.

**Comment by mike-hunhoff** [comment]
we can then write rules like:

```yaml
rule:
  meta:
    name: manipulate files in dotnet
    namespace: host-interaction/file-system
    scope: function
  features:
    - and:
      - class: System.IO.File
```
