### ISSUE TITLE
output/doc missing description for offsets

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#102]
capa match snippet:

```
parse PE header (8 matches)
...
function @ 0x1000B090
  or:
    and:
      mnemonic: cmp @ 0x1000B09C, 0x1000B0B8, 0x1000B12B
      or:
        number: 0x4550 = IMAGE_DOS_SIGNATURE (MZ) @ 0x1000B0B8
      or:
        number: 0x5A4D = IMAGE_NT_SIGNATURE (PE) @ 0x1000B097
    and:
      or:
        and:
          offset: 0x50 @ 0x1000B0D2, 0x1000B0F1
          offset: 0x34 @ 0x1000B0D5, 0x1000B1A3, 0x1000B1B0
...
```

rule snippet:

```
rule:
  meta:
    name: parse PE header
...
        - or:
          - and:  # 32-bit
            - offset: 0x50 = IMAGE_NT_HEADERS.OptionalHeader.SizeOfImage
            - offset: 0x34 = IMAGE_NT_HEADERS.OptionalHeader.ImageBase
...
```

doc snippet:

```
...
                      "children": [
                        {
                          "children": [],
                          "locations": [
                            268480722,
                            268480753
                          ],
                          "node": {
                            "feature": {
                              "offset": "0x50",
                              "type": "offset"
                            },
                            "type": "feature"
                          },
                          "success": true
                        },
                        {
                          "children": [],
                          "locations": [
                            268480725,
                            268480931,
                            268480944
                          ],
                          "node": {
                            "feature": {
                              "offset": "0x34",
                              "type": "offset"
                            },
                            "type": "feature"
                          },
                          "success": true
                        }
                      ],
...
```
