### ISSUE TITLE
dotnet: extract array data

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1099]
see https://github.com/mandiant/capa-rules/issues/591.

we can probably use existing `bytes` feature for this.

**Comment by williballenthin** [comment]
agree that using `bytes` makes sense for a u8 array. not sure what to do for non-u8 arrays, or if this even matters in the real world? i suppose for things like u32 arrays we could serialize them into a `bytes` sequence as might be done in native code.

**Comment by mike-hunhoff** [comment]
hmmm we could allow users to specify array type, supporting a subset like un/signed 8-, 16-, 32-, 64-bit integers?

```yaml
- array[int]: -1, 0, 1, 2
- array[uchar]: 0x41, 0x42, 0x43

- array/int: -1, 0, 1, 2
- array/uchar: 0x41, 0x42, 0x43

- list[s32]: -1, 0, 1, 2
- list[u8]: 0x41, 0x42, 0x43

- list/s32: -1, 0, 1, 2
- list/u8: 0x41, 0x42, 0x43 
```

do we allow `substring`-like functionality?

```yaml
- subarray[int]: -1, 0, 1, 2
- subarray[uchar]: 0x41, 0x42, 0x43

- subarray/int: -1, 0, 1, 2
- subarray/uchar: 0x41, 0x42, 0x43

- sublist[s32]: -1, 0, 1, 2
- sublist[u8]: 0x41, 0x42, 0x43

- sublist/s32: -1, 0, 1, 2
- sublist/u8: 0x41, 0x42, 0x43
```

we could serialize everything to bytes under the hood to make matching less complicated?
