### ISSUE TITLE
dotnet: emit features for ldftn/ldvirftn instructions

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1117]
- `ldftn`: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.ldftn?view=net-6.0
- `ldvirftn`: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.ldvirtftn?view=net-6.0

e.g.

```
... ldftn     instance void malware.methods::timer_callback(object)
... newobj    instance void [mscorlib]System.Threading.TimerCallback::.ctor(object, native int)
```

emit

```yaml
- namespace: malware
- class: malware.methods
- function-name: malware.methods::timer_callback
```
