### ISSUE TITLE
consider changing api feature name

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1130]
As we extend capa to support more technologies/languages the feature name `api` may become confusing. For example, one could argue a class can be considered (or part of) an API blurring the distinction between the `class` and `api` features. Furthermore, it's difficult based on feature names alone to distinguish those that detect transfer of execution (`api`) from those that detect reference (`import`, `export`, `function-name`, `class`, `namespace`, etc.).

Changing the feature name `api` to `call` should help avoid confusion as `call` more clearly indicates the feature detects transfer of execution.

current:

```yaml
- api: kernel32.CreateMutex
- import: kernel32.CreateFile
```

proposed:

```yaml
- call: kernel32.CreateMutex
- import: kernel32.CreateFile
```

Alternatives to consider include `function-call`, `execute`, and `exec`:

```yaml
- function-call: kernel32.CreateMutex
 
- execute: kernel32.CreateMutex

- exec: kernel32.CreateMutex
```
