### ISSUE TITLE
C# code to features

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1135]
Most analysts will read decompiled C# code. Can we A) create an utility to parse code segments to features (e.g. using capa-scripts portions) or B) even better allow to include verbatim C# code in rules?

## A)
Given a code line
```c#
HttpWebRequest r = System.Net.WebRequest.Create(<url>)
r.Method = "Get";
```
We extract the respective features.

## B)
```yaml
- features:
  - code: >
              HttpWebRequest r = System.Net.WebRequest.Create(<url>)
              r.Method = "Get";
```

This idea came to me from here:

Ok, I'm having trouble following this. Can you include a comment of an example code snippet?

_Originally posted by @mr-tz in https://github.com/mandiant/capa-rules/pull/601#discussion_r942190106_
