### ISSUE TITLE
Refactor: extend Feature with access attribute

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1142]
Taking this a step further - would it make sense to extend the [Feature](https://github.com/mandiant/capa/blob/81cb4b31e1025cdc14abdee13bdd92e4949c18dc/capa/features/common.py#L94-L146) class to support an "access" attribute similar to the `bitness` attribute that we previously supported (https://github.com/mandiant/capa/commit/55a5d10859e0a0e0d046c621bb4985faf9769e20).

where the "access" attribute is a simple enum e.g.:

```python
class Access(Enum):
    Read = 1
    Write = 2
```

This would enable us to (optionally) extend the read/write specifier to all current features, including `Property`, and future features. This may even help reduce FPs e.g. the difference between `cmp` and `mov` using a `number` feature to detect PE parsing (we'd likely expect the number 0x5A4D to be read, not written, in this case) e.g.

```yaml
- number/read: 0x5A4D
```

We currently use `mnemonic` features to accomplish the above example but that doesn't easily allow for technology-agnostic rules e.g. a rule author wants to detect when the `number` 0x5A4D is read by both native PE and .NET executables.

_Originally posted by @mike-hunhoff in https://github.com/mandiant/capa/pull/1122#discussion_r943722740_

**Comment by mike-hunhoff** [comment]
@mr-tz also suggested this may be a more generic way to represent `operand` features e.g.:

before

```yaml
        - instruction:
          - mnemonic: xor
          - operand[1].number: 0xEDB88320
```

after

```yaml
        - instruction:
          - mnemonic: xor
          - number/read: 0xEDB88320
```

or pending https://github.com/mandiant/capa/discussions/1125#discussioncomment-3377649:

```yaml
        - instruction:
          - mnemonic: xor
          - constant/read: 0xEDB88320
```
