### ISSUE TITLE
dotnet: consider adding support for "class" or "type" scope

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1259]
e.g. detecting service classes using something like

```yaml
- class:
  - extends: System.ServiceProcess.ServiceBase
  - optional:
    - api: OnStart
    - api: OnStop
    - api: OnPause
    - api: OnContinue
```
doc: https://learn.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicebase?view=dotnet-plat-ext-7.0
