### ISSUE TITLE
Potentially unreliable feature extraction on ELF sample

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1268]
When running below rule on 294b8db1f2702b60fb2e42fdc50c2cee6a5046112da9a5703a548a4fa50477bc vivisect sometimes extract the `localtime` api feature and sometimes it doesn't. Is there a bug in the extractor, vivisect, or elsewhere?

```
rule:
  meta:
    name: get system time on Linux
    namespace: host-interaction/os/info
    authors:
      - "@ramen0x3f"
    scope: function
    examples:
      - 294b8db1f2702b60fb2e42fdc50c2cee6a5046112da9a5703a548a4fa50477bc:0x404970
  features:
    - and:
      - os: linux
      - or:
        - api: localtime
```

ref: https://github.com/mandiant/capa-rules/pull/654
