### ISSUE TITLE
update rule syntax to support scope specification for dynamic analysis flavor

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1539]
as described in https://github.com/mandiant/capa/discussions/1517#discussioncomment-6099387, update the rule syntax to support the rule metadata structure like:

```yml
rule:
  meta:
    name: create file
    scope: 
      - static: function
      - dynamic: thread
  features:
    or:
      api: CreateFile
      api: fopen
```

this will require changes in a bunch of places, including:

- [x] documentation
- [x] yaml parser/validator
- [x] result document metadata structure
- [x] serializer/deserializer

this issue doesn't describe how capa uses the scope specifier - only that it can parse rules with this new syntax.

while this feature is in development, its ok to map rules with `rule.meta.scope: XXX` to `rule.meta.scope.static: XXX` and `rule.meta.scope.dynamic: thread`. we can do a cleanup of the capa-rules once this feature works well.

the PR should be accompanied by test cases that show what happen when invalid syntax is encountered, such as unknown scope names.
