### ISSUE TITLE
update rule syntax to support subscopes in dynamic analysis flavor

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1540]
following #1539, update the rule syntax, parser, and validator to accept subscope statements in the dynamic analysis flavor, such as:

```yml
rule:
  meta:
    scope:
      dynamic: process
  features:
    and:
      thread:
        api: CreateFile
      thread:
        api: RegSetValueExA
```
