### ISSUE TITLE
design features that describe HBIs and NBIs extracted by sandboxes

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1549]
many sandboxes provide a summary of the indicators extracted during runtime analysis, such as files written, registry keys opened, network connections created, etc.

it might be nice to provide a way to match on these indicators in the dynamic analysis flavor of capa. for example:

```yml
  - or:
    - dns: google.com
    - dns: yahoo.com
```

should we do this? what are the benefits? do they outweigh the cost of implementation and documentation?

what are the features that we should add? create subissues for designing those.

**Comment by yelhamer** [comment]
Initially I was thinking of using the wirshark-filter/tshark filtering language, since I believe that'd give rule authors great expressability; however, I think the syntax for that wouldn't be very capa-esque, and it might be hard to determine if two of such statements are equivalent:

```yaml
- network-filter: dns && dns.qry.name contains "iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea.com"
```

the upside however is that we could parse the pcap file using such filters, using something like [pyshark](https://github.com/KimiNewt/pyshark) perhaps.

maybe add some of the most common network features such as ip, dns, and protocol, and then add the *network-filter* option for users that want to parse the pcap?

**Comment by williballenthin** [comment]
does this duplicate the things we can already express with dynamic capa rules? for example, we can imagine `file-write: foo.db` can also be expressed by a dynamic rule like:

```yml
  - and:
    - api: CreateFileW
    - string: "foo.db"
```

or with call scope:

```yml
  - call:
    - api: CreateFileW
    - lpwsPath: "foo.db"
```
