### ISSUE TITLE
design filename HBI feature for use in dynamic analysis

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1559]

**Comment by yelhamer** [comment]
For this feature, I propose to have a syntax similar to that of other HBI-based features; that is, a `filename` keyword that has modifiers (read, write, delete). Additionally, I think it would be a nice addition to support UNIX-like wildcards such as: **?**, **\***, and **{}**. Example:
```yaml
rule:
  meta:
    name: persistence via ssh
    scope: file
  features:
    - filename/write: "/home/*/.ssh/authorized_keys"
```
Another example:
```yaml
rule:
  meta:
    name: persistence via cron
    scope: file
  features:
    - filename/write: "/etc/cron.{daily,hourly,monthly,weekly}/*"
```

The pros are that this format is widely known, in addition to it being easy to parse — as opposed to regex — and quite expressive.
These features could also be extracted at _call_ or _instruction_ scope levels.
