### ISSUE TITLE
Dynamic call scope: add a feature for extracting repeated api calls

### ISSUE THREAD

**Issue by yelhamer** [mandiant/capa#1688]
CAPE provides the number of times an api call was repeated. This might be useful for rule authors (detecting API hammering, profiling malware fa)

I propose either adding a `repeated` feature, or adding a `characteristic("api-hammering")` feature.

of the two I feel like the first would be better, since if we opt for a characteristic feature we'd need to define the minimal bound for the repeats, which I feel like would be variant across samples/families (not sure about this however).

Example rule:

```yaml
rule:
  meta:
    name: API hammering
    scopes:
      dynamic: thread
    examples:
    - 83e921d6368baade50bb2a1031efd6bc # Nymaim
  features:
    - call:
      - api: EnumDisplaySettingsA
      - repeated: 500 or more
```

**Comment by williballenthin** [comment]
like @mr-tz we do support `count(api(EnumDisplaySettingsA))` today; however, this relies on there being unique addresses for each of the things being counted. in the event data that @yelhamer mentions, a single event corresponds to many API calls. we don't have a way to tag the count directly on the API call today.

i'm leaning towards introducing the characteristic, for a few reasons:
  1. we can provide a reasonable default value, since rule authors probably don't need to varying this number from rule to rule
  2. its easy to add a new characteristic, much harder to add a new syntax

i think the following should be doable:


```yaml
- call:
  - api: EnumDisplaySettingsA
  - characteristic: api-hammering
```
