### ISSUE TITLE
Offset feature to account for read/write access of operand

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#359]
### Summary

Include if an offset is read from or written to. Add additional modifier to feature such as:
- `- offset/r` or `- offset/w`

Could become confusing with the already existing `x32`/`x64` modifiers. If you can think of a better syntax, please comment below.

### Motivation

Allow for more concrete rules and avoid false positives. For example, observed frequently with `parse PE header` rule.

Imagine something like:
```yaml
        - or:
          - and:
            - offset/r/x32: 0x50 = IMAGE_NT_HEADERS.OptionalHeader.SizeOfImage
            - offset/r/x32: 0x34 = IMAGE_NT_HEADERS.OptionalHeader.ImageBase
          - and:
            - offset/r/x64: 0x50 = IMAGE_NT_HEADERS64.OptionalHeader.SizeOfImage
            - offset/r/x64: 0x30 = IMAGE_NT_HEADERS64.OptionalHeader.ImageBase
```

## Additional context

Related issue: #210
