### ISSUE TITLE
count basic block

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#78]
This rule is not working as I expect, I get no results. Am I using this wrong?

```
rule:
  meta:
    name: count bb
    namespace: test
    scope: function
  features:
    - and:
      - count(basic blocks): 1 or more
```
