### ISSUE TITLE
add capafmt utility for consistent formatting of rules

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#8]
it would be nice to format rules with a consistent style.

this includes:
  - whitespacing, especially with lists
  - order `meta` before `features`

by default, python yaml emits keys alphabetically. as an example:

```
rule:
  meta:
    att&ck:
    - Defense Evasion::Obfuscated Files or Information T1027.002
    author: william.ballenthin@fireeye.com
    examples:
    - CD2CBA9E6313E8DF2C1273593E649682
    - Practical Malware Analysis Lab 01-02.exe_:0x0401000
    mbc:
    - Anti-Static Analysis::Software Packing
    name: packed with UPX
    namespace: anti-analysis/packer/upx
    scope: file
  features:
  - or:
    - section: UPX0
    - section: UPX1
```

this wold look nicer:

```
rule:
  meta:
    name: packed with UPX
    namespace: anti-analysis/packer/upx
    author: william.ballenthin@fireeye.com
    att&ck:
    - Defense Evasion::Obfuscated Files or Information T1027.002
    mbc:
    - Anti-Static Analysis::Software Packing
    examples:
    - CD2CBA9E6313E8DF2C1273593E649682
    - Practical Malware Analysis Lab 01-02.exe_:0x0401000
    scope: file
  features:
  - or:
    - section: UPX0
    - section: UPX1
```
