### ISSUE TITLE
probably don't use global features (arch/os/format) to optimize rule matching

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#931]
we currently optimize rule matching by downselecting from all rules to the rules that could potentially match, using the presence of features referenced in those rules. we probably don't want to use arch/os/format features to do this downselection. i dont know if we want to hardcode this, or if there's some other policy way of doing it.

**Comment by mr-tz** [comment]
one idea: move `arch`, `os`, etc. to the `meta` section? most rules use them under a top-level `and` IIRC

pro:
- quickly filter out rules

con:
- duplication in some abstraction rules (negligible, I think)

**Comment by williballenthin** [comment]
we support these global features so we can do things like:

```yaml
- or:
  - and:
    - arch: i386
    - offset: 4
  - and:
    - arch: amd64
    - offset: 8        
```
which i think is pretty elegant. this was discussed in https://github.com/mandiant/capa/discussions/701
