### ISSUE TITLE
dotnet: consider emitting references to types

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#982]
methods interact with various types, including both primitive objects (u8) and classes. sometimes we see method/property access to the classes, which can be represented by things like `API` (and maybe `offset`???). we might also see direct references to class objects, such as casting instances from one class to another.

do we want to introduce a new feature to represent types/classes referenced within some scope?

e.g.

```yaml
type: System.Net.FtpWebResponse
```

**Comment by williballenthin** [comment]
> I vote we boot #982 to the next release. #982 ties in with some other .NET feature parsing I believe we will need more research and discussion on before implementing.

@mike-hunhoff

**Comment by mike-hunhoff** [comment]
track `CIL` instructions:
- `newobj`: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.newobj?view=net-6.0
- `castclass`: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.castclass?view=net-6.0
- `initobj`: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.initobj?view=net-6.0

**Comment by mike-hunhoff** [comment]
we may be able to emit `namespace` and `class` features for type references, like we do for method calls e.g.

```
... newobj    instance void [System]System.Uri::.ctor(string)
```

```
- namespace: System
- class: System.Uri
```

**Comment by mike-hunhoff** [comment]
the proposal above does not allow us to capture object creation e.g.

```
... newobj    instance void [mscorlib]System.Threading.Mutex::.ctor(bool, string, bool&)
```

we could emit this as a new `type` feature, as Willi suggested, or maybe a new `instance` feature e.g.

```yaml
rule:
  meta:
    name: create mutex using .NET
    ...
  features:
     - or:
       - instance: System.Threading.Mutex
       ...
```

I think I prefer `instance` to better communicate the object has been created, versus `type` which I think we can represent using the existing `namespace` and `class` features e.g. for the snippet above emit

```yaml
- namespace: System.Threading
- class: System.Threading.Mutex
- instance: System.Threading.Mutex
```

unsure about the overlap of `class` and `instance` but I think this allows rule authors to write more intentional rules e.g. we can distinguish between "manipulate mutex using .NET" w/ `-class: System.Threading.Mutex` and "create mutex using.NET" w/ `-instance: System.Threading.Mutex`.

**Comment by mike-hunhoff** [comment]
another use case for an `instance` feature:

```
... newobj    instance void [mscorlib]System.Reflection.Emit.DynamicMethod::.ctor(string, class [mscorlib]System.Type, class [mscorlib]System.Type[], class [mscorlib]System.Type, bool)
```

```yaml
- namespace: System.Reflection.Emit
- class: System.Reflection.Emit.DynamicMethod
- instance: System.Reflection.Emit.DynamicMethod
```
